permalink   : /:categories/:year/:title/
markdown    : kramdown
highlight : true

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: 北京九章云极科技有限公司
description: "Front end team"
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "https://9web.github.io/"
repository: "https://github.com/9web/9web.github.io"
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1


gems: [jekyll-paginate]
# social footer
#social:
#  github:
#    slug: github
#    link: http://github.com/nandomoreirame
#  facebook:
#    slug: facebook
#    link: http://facebook.com/fernando.dev
#  twitter:
#    slug: twitter
#    link: http://twitter.com/nandomoreirame
# instagram:
#    slug: instagram
#    link: http://instagram.com/nandomoreira.me
#  linkedin:
#    slug: linkedin
#    link: http://linkedin.com/in/nandomoreirame